# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Big Data Real-Time Analytics com Python e Spark</font>

# <font color='blue'>Capítulo 2</font>

Para gerar um arquivo pdf a partir do Jupyter Notebook, você precisar ter instalado em seu computador:
    
    MiKTeX e Pandoc (Windows)
    LaTeX e Pandoc (Mac)
    TeX Live e Pandoc (linux)
    
Neste link você encontra todas as informações: http://pandoc.org/installing.html

## Computação com Numpy

In [1]:
# Importando o módulo Numpy
import numpy as np

<h2>Criando Estruturas de Dados NumPy</h2>

In [2]:
# Criando array unidimensional
array1 = np.array([10, 20, 30, 40]) 

In [3]:
# Criando array bi-dimensional
array2 = np.array([[100, 83, 15],[42, 78, 0]]) 

In [4]:
array1

array([10, 20, 30, 40])

In [5]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [6]:
# Verificando o formato (shape) do array
array1.shape

(4,)

In [7]:
# Verificando o formato (shape) do array
array2.shape

(2, 3)

In [8]:
# Verificando o número de dimensões
array2.ndim

2

<h2>Em Python TUDO é objeto, com métodos e atributos</h2>

### Método - realiza ação no objeto
### Atributo - característica do objeto

In [9]:
# Método
array2.max()

100

In [10]:
# Atributo
array2.ndim

2

<h2>Criando estruturas de dados com arange</h2>

In [11]:
array3 = np.arange(15)

In [12]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# Usando start/end (exclusive)
array4 = np.arange(0, 15, 5)

In [14]:
array4

array([ 0,  5, 10])

<h2>Criando estruturas de dados com linspace</h2>

In [15]:
# Argumentos: (start, end, number of elements)
array5 = np.linspace(0, 3, 4); array5

array([0., 1., 2., 3.])

<h2>Criando estruturas de dados com outras funções</h2>

<h3>numpy.zeros</h3>

In [16]:
# Array 10x8 de zeros
array6 = np.zeros((10, 8)); array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

<h3>numpy.ones</h3>

In [17]:
# Array 2x3x2 de 1's
array7 = np.ones((2, 3, 2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

<h3>numpy.eye</h3>

In [18]:
# Produz uma Identitiy Matrix 
array8 = np.eye(3); array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h3>numpy.diag</h3>

In [19]:
# Matriz diagonal
array9 = np.diag((2,1,4,6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

<h3>numpy.random.rand</h3>

In [20]:
# A função rand(n) produz uma sequência de números uniformemente distribuídos com range de 0 a n
np.random.seed(100) # Set seed
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [21]:
# A função randn(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

<h3>numpy.empty</h3>

In [22]:
array12 = np.empty((3,2)); array12

array([[0.00000000e+000, 0.00000000e+000],
       [1.77229088e-310, 3.50977866e+064],
       [0.00000000e+000, 0.00000000e+000]])

<h3>numpy.tile</h3>

In [23]:
np.array([[9, 4], [3, 7]])

array([[9, 4],
       [3, 7]])

In [24]:
np.tile(np.array([[9, 4], [3, 7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [25]:
np.tile(np.array([[9, 4], [3, 7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

<h2>Tipos de Dados NumPy</h2>

In [26]:
array13 = np.array([8, -3, 5, 9], dtype = 'float')

In [27]:
array13

array([ 8., -3.,  5.,  9.])

In [28]:
array13.dtype

dtype('float64')

In [29]:
array14 = np.array([2, 4, 6, 8])

In [30]:
array14

array([2, 4, 6, 8])

In [31]:
array14.dtype

dtype('int64')

In [32]:
array15 = np.array([2.0, 4, 6, 8])

In [33]:
array15.dtype

dtype('float64')

In [34]:
array16 = np.array(['Análise','de','Dados','com Python'])

In [35]:
array16.dtype

dtype('<U10')

In [36]:
array17 = np.array([True, False, True])

In [37]:
array17.dtype

dtype('bool')

In [38]:
array18 = np.array([7, -3, 5.24])

In [39]:
array18.dtype

dtype('float64')

In [40]:
array18.astype(int)

array([ 7, -3,  5])

<h2>Operações com Arrays</h2>

In [41]:
# Array começando por 0, com 30 elementos e multiplicado po 5
array19 = np.arange(0, 30) * 5

In [42]:
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [43]:
array19 = np.arange(0, 30)

In [44]:
array19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
# Elevando um array a potência
array20 = np.arange(5) ** 4

In [46]:
array20

array([  0,   1,  16,  81, 256])

In [47]:
# Somando um número a cada elemento do array
array21 = np.arange(0, 30) + 1

In [48]:
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
array22 = np.arange(0, 30,3) + 3
array23 = np.arange(1,11)

In [50]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [51]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
# Subtração
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [53]:
# Soma
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [54]:
# Divisão
array22 / array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [55]:
# Multiplicação
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [56]:
# Podemos ainda comparar arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [57]:
arr1 = np.array([True,False,True,False])
arr2 = np.array([False,False,True, False])
np.logical_and(arr1, arr2)

array([False, False,  True, False])

### Podemos criar arrays com Python, sem usar o módulo NumPy. Porém o NumPy é muito mais rápido

In [58]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

3.24 µs ± 28.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [59]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

350 µs ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


A métrica µs significa microsegundos.

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>