In [1]:
import numpy as np

### Array Concatenation

In [2]:
arr_01 = np.ones(4)

In [3]:
arr_02 = np.arange(15)

In [5]:
arr_concat = np.concatenate((arr_01, arr_02))

In [6]:
arr_concat

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

### Array Joining

In [14]:
arr_01 = np.zeros((3, 3)); arr_01

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr_02 = np.ones((3, 3)); arr_02

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# ?np.vstack
np.vstack((arr_01, arr_02))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# ?np.hstack
np.hstack((arr_01, arr_02))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [27]:
arr_01 = np.array([1, 2, 3])
arr_02 = np.array([4, 5, 6])
arr_03 = np.array([7, 8, 9])

In [28]:
# ?np.column_stack
np.column_stack((arr_01, arr_02, arr_03))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
# ?np.row_stack
np.row_stack((arr_03, arr_02, arr_01))

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

### Array Spliting

In [33]:
arr = np.arange(16).reshape((4, 4)); arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
# ?np.hsplit
[arr_p1, arr_p2] = np.hsplit(arr, 2)

In [42]:
arr_p1, arr_p2

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [46]:
# ?np.vsplit
[arr_p1, arr_p2] = np.vsplit(arr, 2)

In [47]:
arr_p1, arr_p2

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))