# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Big Data Real-Time Analytics com Python e Spark</font>

# <font color='blue'>Capítulo 3</font>

## NumPy

NumPy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]


'1.16.2'

In [2]:
# Criando um array NumPy
array1 = np.arange(15)

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Help
?array1

In [5]:
array1.mean()

7.0

In [6]:
array1.sum()

105

In [7]:
array1.min()

0

In [8]:
array1.max()

14

In [9]:
array1.std()

4.320493798938574

## Utilizando List Compreheension em Arrays NumPy

In [10]:
# Utilizando list compreheension em arrays NumPy
[x * x for x in array1]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [11]:
# Utilizando list compreheension em arrays NumPy
[x * x for x in array1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

## Utilizando Função Lambda em Arrays NumPy

In [12]:
# Utilizando expressão lambda
list(filter(lambda x: x % 2 == 0, array1))

[0, 2, 4, 6, 8, 10, 12, 14]

In [13]:
# Atenção com a notação
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [14]:
# # Atenção com a notação
array1[array1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

## Avaliando a Performance

In [15]:
# Performance usando list compreheension
%timeit [x for x in array1 if x % 2 == 0]

6.03 µs ± 135 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
# Performance usando NumPy
%timeit array1[array1 % 2 == 0]

2.16 µs ± 65.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Usando Operadores Lógicos

In [17]:
array1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [18]:
array1[array1 > 8]

array([ 9, 10, 11, 12, 13, 14])

In [19]:
# Operador lógico and 
(array1 > 9) & (array1 < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [20]:
# Operador lógico or
(array1 > 13) | (array1 < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True])

In [21]:
# Operador lógico or
array1[(array1 > 13) | (array1 < 12)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14])

In [22]:
# Criando um array NumPy com list comprehension
array2 = np.array([x ** 3 for x in range(15)])

In [23]:
array2

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [24]:
# Criando um array NumPy com list comprehension
array2 = np.array([True for x in range(15)])

In [25]:
array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [26]:
# Usando um array como índice para outro array
array1[array2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>