In [1]:
import sys
import numpy as np

In [2]:
sys.version

'3.7.6 (default, Jan  8 2020, 19:59:22) \n[GCC 7.3.0]'

In [3]:
np.__version__

'1.18.1'

### NumPy Array

In [4]:
arr_np = np.arange(15)

In [5]:
arr_np

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr_np.min()

0

In [7]:
arr_np.max()

14

In [8]:
arr_np.sum()

105

In [9]:
arr_np.mean()

7.0

In [10]:
# For help:
# ?arr_np

### With List Compreheension

In [11]:
[x * x for x in arr_np]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [12]:
[x * x for x in arr_np if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

### With Lambda Function

In [13]:
list(filter(lambda x: x % 2 == 0, arr_np))

[0, 2, 4, 6, 8, 10, 12, 14]

In [14]:
# NumPy Notation for mapping even values of "arr_np"
[arr_np % 2 == 0]

[array([ True, False,  True, False,  True, False,  True, False,  True,
        False,  True, False,  True, False,  True])]

In [15]:
# Numpy notation to get the same results of cells 12 and 13 (with pure Python notation)
arr_np[arr_np % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### Performance Evaluation

In [16]:
# With Python
%timeit [x for x in arr_np if x % 2 == 0]

15.5 µs ± 1.34 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
# With Python + NumPy
%timeit arr_np[arr_np % 2 == 0]

4.27 µs ± 61.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Logical Operators

In [18]:
arr_np > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [19]:
arr_np[arr_np > 8]

array([ 9, 10, 11, 12, 13, 14])

In [20]:
(arr_np > 9) & (arr_np < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [21]:
(arr_np > 13) | (arr_np < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True])

In [22]:
arr_np[(arr_np > 13) | (arr_np < 12)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14])

In [23]:
arr_np_2 = np.array([True if x % 2 == 0 else False for x in range(15)])

In [24]:
arr_np_2

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [25]:
arr_np[arr_np_2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])