In [1]:
import numpy as np

### One-dimensional array

In [2]:
arr_01 = np.array([10, 20, 30])

In [3]:
arr_01

array([10, 20, 30])

### Multi dimensional array

In [4]:
arr_02 = np.array([[10, 20, 30], [40, 50, 60]])

In [5]:
arr_02

array([[10, 20, 30],
       [40, 50, 60]])

### Checking arrays shapes (y, x)

In [6]:
arr_01.shape

(3,)

In [7]:
arr_02.shape

(2, 3)

### Checking arrays dimensions

In [8]:
arr_01.ndim

1

In [9]:
arr_02.ndim

2

### Arrays attributes

In [10]:
arr_01.dtype

dtype('int64')

In [11]:
arr_02.size

6

### Arrays functions

In [12]:
arr_01.min()

10

In [13]:
arr_02.max()

60

### Data Structures

In [14]:
arr_03 = np.arange(10)

In [15]:
arr_03

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr_04 = np.arange(2, 10, 2)

In [17]:
arr_04

array([2, 4, 6, 8])

In [18]:
arr_05 = np.linspace(0, 1, 3)

In [19]:
arr_05

array([0. , 0.5, 1. ])

In [20]:
arr_06 = np.zeros((5, 3))

In [21]:
arr_06

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr_07 = np.ones((5, 3))

In [23]:
arr_07

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr_08 = np.eye(3)

In [25]:
arr_08

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
arr_09 = np.diag((1, 3, 5))

In [27]:
arr_09

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [28]:
arr_10 = np.random.rand(3, 2)

In [29]:
arr_10

array([[0.03117196, 0.76415818],
       [0.84464849, 0.77021359],
       [0.65864565, 0.24986813]])

In [30]:
arr_11 = np.empty((3, 2))

In [31]:
arr_11

array([[0.03117196, 0.76415818],
       [0.84464849, 0.77021359],
       [0.65864565, 0.24986813]])

In [32]:
arr_12 = np.array([[9, 4], [3, 7]])

In [33]:
arr_12

array([[9, 4],
       [3, 7]])

In [34]:
np.tile(arr_12, [3])

array([[9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7]])

In [35]:
np.tile(arr_12, [2, 2])

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

### Data Types

In [36]:
arr_13 = np.array([1, 2, 3])

In [37]:
arr_13.dtype

dtype('int64')

In [38]:
arr_14 = np.array([1, 2, 3], dtype = 'float')

In [39]:
arr_14.dtype

dtype('float64')

In [40]:
arr_15 = np.array([1, 2.5, 3])

In [41]:
arr_15.dtype

dtype('float64')

In [42]:
arr_16 = np.array(['data', 'science'])

In [43]:
arr_16.dtype

dtype('<U7')

In [44]:
arr_17 = np.array([True, False, True])

In [45]:
arr_17.dtype

dtype('bool')

In [46]:
arr_18 = np.array([7, -5, 3.4])

In [47]:
arr_18.dtype

dtype('float64')

In [48]:
arr_18.astype(int)

array([ 7, -5,  3])

### Operations

In [49]:
arr_19 = np.arange(1, 5) * 10

In [50]:
arr_19

array([10, 20, 30, 40])

In [51]:
arr_20 = np.arange(1, 5) ** 2

In [52]:
arr_20

array([ 1,  4,  9, 16])

In [53]:
arr_21 = np.arange(0, 4) + 1

In [54]:
arr_21

array([1, 2, 3, 4])

In [55]:
arr_22 = np.arange(5) * 5

In [56]:
arr_22

array([ 0,  5, 10, 15, 20])

In [57]:
arr_23 = np.arange(5)

In [58]:
arr_23

array([0, 1, 2, 3, 4])

In [59]:
arr_22 - arr_23

array([ 0,  4,  8, 12, 16])

In [60]:
arr_22 > arr_23

array([False,  True,  True,  True,  True])

In [61]:
arr_24 = np.array([True,  False, True])
arr_25 = np.array([False, False,  True])

In [62]:
np.logical_and(arr_24, arr_25)

array([False, False,  True])

In [63]:
np.logical_or(arr_24, arr_25)

array([ True, False,  True])

### Comparing Python and Numpy arrays performances

In [64]:
arr_np = np.arange(1000)

%timeit arr_np ** 4

6.89 µs ± 668 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [65]:
arr_py = range(1000)

%timeit [arr_py[i] ** 4 for i in arr_py]

654 µs ± 90 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
