In [1]:
import numpy as np

### Transposition

In [2]:
arr_01 = np.array([[10, 20, 30], [40, 50, 60]])

In [3]:
arr_01

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
arr_01.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [5]:
np.transpose(arr_01)

array([[10, 40],
       [20, 50],
       [30, 60]])

### Boradcasting

In [6]:
arr_02 = np.array([[1, 2, 3]])

In [7]:
arr_02

array([[1, 2, 3]])

In [8]:
arr_02.T

array([[1],
       [2],
       [3]])

In [9]:
arr_02.T + arr_02

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### Arrays to Matrices

In [10]:
arr_03 = np.array([np.arange(1, 6), np.arange(10, 15)])

In [11]:
arr_03

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [12]:
arr_03.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [13]:
arr_03.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

### Logical Operators

In [14]:
np.random.seed(100)

In [15]:
arr_04 = np.random.randint(1, 10, size = (4, 4))

In [16]:
arr_04

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [17]:
np.any(arr_04 % 7 == 0)

False

In [18]:
np.all(arr_04 < 11)

True

### Reshaping

In [19]:
arr_05 = np.arange(1, 16)

In [20]:
arr_05

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
arr_05.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Ordering

In [22]:
arr_06 = np.array([[40, 30], [20, 10]])

In [23]:
arr_06

array([[40, 30],
       [20, 10]])

In [24]:
arr_06.sort(axis = 1)

In [25]:
arr_06

array([[30, 40],
       [10, 20]])

In [26]:
arr_06.sort(axis = 0)

In [27]:
arr_06

array([[10, 20],
       [30, 40]])